# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Y:\tmp\vrep_project\vrep_test\vrep\VT_v01.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(591, 241)
        self.with_start = QtWidgets.QPushButton(Form)
        self.with_start.setGeometry(QtCore.QRect(400, 20, 81, 31))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.with_start.setFont(font)
        self.with_start.setObjectName("with_start")
        self.with_return = QtWidgets.QPushButton(Form)
        self.with_return.setGeometry(QtCore.QRect(490, 20, 81, 31))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.with_return.setFont(font)
        self.with_return.setObjectName("with_return")
        self.label_results_window = QtWidgets.QLabel(Form)
        self.label_results_window.setGeometry(QtCore.QRect(300, 60, 91, 31))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_results_window.setFont(font)
        self.label_results_window.setObjectName("label_results_window")
        self.label_button = QtWidgets.QLabel(Form)
        self.label_button.setGeometry(QtCore.QRect(300, 19, 91, 31))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_button.setFont(font)
        self.label_button.setObjectName("label_button")
        self.listWidget_results_window = QtWidgets.QListWidget(Form)
        self.listWidget_results_window.setGeometry(QtCore.QRect(300, 90, 271, 131))
        self.listWidget_results_window.setObjectName("listWidget_results_window")
        self.formLayoutWidget = QtWidgets.QWidget(Form)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 90, 251, 134))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.form_3d = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.form_3d.setContentsMargins(0, 0, 0, 0)
        self.form_3d.setObjectName("form_3d")
        self.label_x = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(16)
        self.label_x.setFont(font)
        self.label_x.setObjectName("label_x")
        self.form_3d.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_x)
        self.value_y = QtWidgets.QDoubleSpinBox(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(20)
        self.value_y.setFont(font)
        self.value_y.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.value_y.setMouseTracking(False)
        self.value_y.setTabletTracking(False)
        self.value_y.setAcceptDrops(False)
        self.value_y.setAutoFillBackground(False)
        self.value_y.setWrapping(False)
        self.value_y.setAccelerated(False)
        self.value_y.setProperty("showGroupSeparator", False)
        self.value_y.setPrefix("")
        self.value_y.setSuffix("")
        self.value_y.setDecimals(1)
        self.value_y.setMinimum(-200.0)
        self.value_y.setMaximum(200.0)
        self.value_y.setSingleStep(1.0)
        self.value_y.setObjectName("value_y")
        self.form_3d.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.value_y)
        self.label_z = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(16)
        self.label_z.setFont(font)
        self.label_z.setObjectName("label_z")
        self.form_3d.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_z)
        self.label_y = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(16)
        self.label_y.setFont(font)
        self.label_y.setObjectName("label_y")
        self.form_3d.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_y)
        self.value_z = QtWidgets.QDoubleSpinBox(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.value_z.sizePolicy().hasHeightForWidth())
        self.value_z.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(20)
        self.value_z.setFont(font)
        self.value_z.setPrefix("")
        self.value_z.setSuffix("")
        self.value_z.setDecimals(1)
        self.value_z.setMinimum(-100.0)
        self.value_z.setSingleStep(1.0)
        self.value_z.setProperty("value", 0.0)
        self.value_z.setObjectName("value_z")
        self.form_3d.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.value_z)
        self.value_x = QtWidgets.QDoubleSpinBox(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(20)
        self.value_x.setFont(font)
        self.value_x.setSuffix("")
        self.value_x.setDecimals(1)
        self.value_x.setMinimum(-200.0)
        self.value_x.setMaximum(200.0)
        self.value_x.setSingleStep(1.0)
        self.value_x.setObjectName("value_x")
        self.form_3d.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.value_x)
        self.label_3d = QtWidgets.QLabel(Form)
        self.label_3d.setGeometry(QtCore.QRect(20, 60, 91, 31))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3d.setFont(font)
        self.label_3d.setObjectName("label_3d")
        self.label_ItemName = QtWidgets.QLabel(Form)
        self.label_ItemName.setGeometry(QtCore.QRect(20, 19, 91, 31))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_ItemName.setFont(font)
        self.label_ItemName.setObjectName("label_ItemName")
        self.ItemName = QtWidgets.QPlainTextEdit(Form)
        self.ItemName.setGeometry(QtCore.QRect(120, 20, 111, 31))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.ItemName.setFont(font)
        self.ItemName.setMaximumBlockCount(1)
        self.ItemName.setObjectName("ItemName")
        self.print = QtWidgets.QPushButton(Form)
        self.print.setGeometry(QtCore.QRect(240, 20, 31, 31))
        self.print.setObjectName("print")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.with_start, self.with_return)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.with_start.setText(_translate("Form", "Start"))
        self.with_return.setText(_translate("Form", "Return"))
        self.label_results_window.setText(_translate("Form", " 輸出結果 :"))
        self.label_button.setText(_translate("Form", " 點擊按鈕 :"))
        self.label_x.setText(_translate("Form", " X (mm)"))
        self.label_z.setText(_translate("Form", " Z (mm)"))
        self.label_y.setText(_translate("Form", " Y (mm)"))
        self.value_z.setToolTip(_translate("Form", "x"))
        self.label_3d.setText(_translate("Form", "移動座標 :"))
        self.label_ItemName.setText(_translate("Form", "物件名稱 :"))
        self.print.setText(_translate("Form", "Print"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

