# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VT_v01.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(322, 191)
        self.pushButton_start = QtWidgets.QPushButton(Form)
        self.pushButton_start.setGeometry(QtCore.QRect(210, 100, 91, 31))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.pushButton_start.setFont(font)
        self.pushButton_start.setObjectName("pushButton_start")
        self.pushButton_return = QtWidgets.QPushButton(Form)
        self.pushButton_return.setGeometry(QtCore.QRect(210, 140, 91, 31))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_return.setFont(font)
        self.pushButton_return.setObjectName("pushButton_return")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 30, 281, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.HLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.HLayout.setContentsMargins(0, 0, 0, 0)
        self.HLayout.setObjectName("HLayout")
        self.value_y = QtWidgets.QDoubleSpinBox(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(10)
        self.value_y.setFont(font)
        self.value_y.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.value_y.setMouseTracking(False)
        self.value_y.setTabletTracking(False)
        self.value_y.setAcceptDrops(False)
        self.value_y.setAutoFillBackground(False)
        self.value_y.setWrapping(False)
        self.value_y.setAccelerated(False)
        self.value_y.setProperty("showGroupSeparator", False)
        self.value_y.setPrefix("")
        self.value_y.setSuffix("")
        self.value_y.setDecimals(1)
        self.value_y.setMinimum(-200.0)
        self.value_y.setMaximum(200.0)
        self.value_y.setSingleStep(0.1)
        self.value_y.setObjectName("value_y")
        self.HLayout.addWidget(self.value_y)
        self.value_x = QtWidgets.QDoubleSpinBox(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(10)
        self.value_x.setFont(font)
        self.value_x.setSuffix("")
        self.value_x.setDecimals(1)
        self.value_x.setMinimum(-200.0)
        self.value_x.setMaximum(200.0)
        self.value_x.setSingleStep(0.1)
        self.value_x.setObjectName("value_x")
        self.HLayout.addWidget(self.value_x)
        self.value_z = QtWidgets.QDoubleSpinBox(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.value_z.sizePolicy().hasHeightForWidth())
        self.value_z.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(10)
        self.value_z.setFont(font)
        self.value_z.setPrefix("")
        self.value_z.setSuffix("")
        self.value_z.setDecimals(1)
        self.value_z.setMinimum(-100.0)
        self.value_z.setSingleStep(0.1)
        self.value_z.setProperty("value", 0.0)
        self.value_z.setObjectName("value_z")
        self.HLayout.addWidget(self.value_z)
        self.value_y.raise_()
        self.value_z.raise_()
        self.value_x.raise_()
        self.label_x = QtWidgets.QLabel(Form)
        self.label_x.setGeometry(QtCore.QRect(20, 20, 47, 12))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(10)
        self.label_x.setFont(font)
        self.label_x.setObjectName("label_x")
        self.label_y = QtWidgets.QLabel(Form)
        self.label_y.setGeometry(QtCore.QRect(120, 20, 47, 12))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(10)
        self.label_y.setFont(font)
        self.label_y.setObjectName("label_y")
        self.label_z = QtWidgets.QLabel(Form)
        self.label_z.setGeometry(QtCore.QRect(210, 20, 47, 12))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(10)
        self.label_z.setFont(font)
        self.label_z.setObjectName("label_z")
        self.label_results_window = QtWidgets.QLabel(Form)
        self.label_results_window.setGeometry(QtCore.QRect(20, 80, 91, 16))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(10)
        self.label_results_window.setFont(font)
        self.label_results_window.setObjectName("label_results_window")
        self.label_button = QtWidgets.QLabel(Form)
        self.label_button.setGeometry(QtCore.QRect(210, 80, 91, 20))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(10)
        self.label_button.setFont(font)
        self.label_button.setObjectName("label_button")
        self.listWidget_results_window = QtWidgets.QListWidget(Form)
        self.listWidget_results_window.setGeometry(QtCore.QRect(20, 100, 181, 71))
        self.listWidget_results_window.setObjectName("listWidget_results_window")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.value_y, self.value_x)
        Form.setTabOrder(self.value_x, self.value_z)
        Form.setTabOrder(self.value_z, self.pushButton_start)
        Form.setTabOrder(self.pushButton_start, self.pushButton_return)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_start.setText(_translate("Form", "Start"))
        self.pushButton_return.setText(_translate("Form", "Return"))
        self.value_z.setToolTip(_translate("Form", "x"))
        self.label_x.setText(_translate("Form", " X (mm)"))
        self.label_y.setText(_translate("Form", "Y (mm)"))
        self.label_z.setText(_translate("Form", " Z (mm)"))
        self.label_results_window.setText(_translate("Form", " 輸出結果 :"))
        self.label_button.setText(_translate("Form", " 點擊按鈕 :"))

